### ISSUE TITLE
Coffee machine turning on via BT protocol

### ISSUE THREAD

**Issue by sergey-gra** [Jutta-Proto/protocol-bt-cpp#10]
Can the coffee machine be powered on via Bluetooth protocol after a power outage? The maximum time available to be in ON mode so appears to be 9 hours. I see that  this can be achieved through the UART protocol. But I want to know is it possible to solve this issue via BT protocol? Or maybe there's a way to disable automatic turn off.

**Comment by COM8** [comment]
As far as I'm aware no. On my former JURA E6 coffee maker I was able to set automatic standby to off. For me it never turned off after that but I have not kept it running for more than six hours at once.

Perhaps one could periodically trigger some kind of action that resets this counter?

**Comment by sergey-gra** [comment]
> On my former JURA E6 coffee maker I was able to set automatic standby to off

Could you please elaborate on the method you used to implement it?

**Comment by sergey-gra** [comment]
> Perhaps one could periodically trigger some kind of action that resets this counter?

Sounds good. Need to try find something like you mentioned.

**Comment by COM8** [comment]
> > On my former JURA E6 coffee maker I was able to set automatic standby to off
> 
> Could you please elaborate on the method you used to implement it?

I used the JURA Joe app for it. There you can change machine settings.

**Comment by sergey-gra** [comment]
> 

Based on my observation of the application, it appears that the maximum duration for the automatic switch-off feature is limited to 9 hours, and there is no provision to completely disable the automatic switch-off feature.
