### ISSUE TITLE
Accessing to setting through BT protocol

### ISSUE THREAD

**Issue by sergey-gra** [Jutta-Proto/protocol-bt-cpp#12]
Greetings, I would like to inquire if there is a method to access the setting for the automatic shutdown feature on the Jura E6 machine. For example to change the duration for AutoOFF. I assume such an option exists, given its inclusion in the JOE mobile application. However, I would appreciate any information you might have on this matter, particularly if you have encountered it before. Thanks in advance.

**Comment by COM8** [comment]
Yes, there are setting, but I have not reverse engineered them yet. There is a `MACHINESETTINGS` section inside the machinefile.
