### ISSUE TITLE
Discrepancy between test_exec and other "tools"/"code"

### ISSUE THREAD

**Issue by mteichtahl** [Jutta-Proto/protocol-bt-cpp#14]
Hi all

I have found an interesting issue. When I grab the manufacturerData from a peripheral, noble is giving me what appears to be incorrect data. Looking at the three samples, you will see the data from noble and bluetoothcli is different from the data returned from test_exec. I believe the data from test_exec to be **correct**. However, even if i hard code the key from test_exec into noble, the hearbeat fails to keep the session alive.

my environment is ```Linux jura 5.15.0-1046-raspi #49-Ubuntu SMP PREEMPT Thu Jan 18 12:45:41 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux``` on ```Ubuntu 22.04.4 LTS```

any guidance would be greatly appreciated

**from noble**
```js
{
  localName: 'TT214H BlueFrog',
  txPowerLevel: undefined,
  manufacturerData: <Buffer ab 00 2a 05 08 03 31 3d e5 2e fa 00 46 43 83 42 01 c0 01 b6 28 00 00 00 00 00 00 00 00>,
  serviceData: [],
  serviceUuids: [ '1523', '1623' ],
  solicitationServiceUuids: [],
  serviceSolicitationUuids: []
}
```

**from bluetoothcli**
```bash
^Croot@jura:/home/amazon/btEngine# bluetoothctl info F8:FB:C3:2A:78:70
Device F8:FB:C3:2A:78:70 (random)
        Name: TT214H BlueFrog
        Alias: TT214H BlueFrog
        Paired: no
        Trusted: no
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Unknown                   (00001523-0000-1000-8000-00805f9b34fb)
        UUID: Unknown                   (00001623-0000-1000-8000-00805f9b34fb)
        ManufacturerData Key: 0x00ab
        ManufacturerData Value:
  2a 05 08 03 31 3d e5 2e fa 00 46 43 83 42 01 c0  *...1=....FC.B..
  01 b6 28 00 00 00 00 00 00 00 00                 ..(........   
```
**From test_exec**

```bash
[  info  ] [thread 55801]       Loading machines...
[  info  ] [thread 55801]       Loaded 543 machines.
[  info  ] [thread 55801]       Loading JOE from 'machinefiles/EF567_c.xml'...
[  info  ] [thread 55801]       JOE loaded.
[  info  ] [thread 55801]       Found machine 'GIGA X3c (INTB)' Version: 6 with 31 products.
[  info  ] [thread 55801]       Sending stay in BLE mode...
[  info  ] [thread 55801]       Key: 42. <---- - 0x2A
[  info  ] [thread 55801]       Wrote: 77656D
[  info  ] [thread 55801]       Connected.
```

the relevant code section is below

```ts
noble.on('discover', async (peripheral: Peripheral)=> {
      if (peripheral.address === CoffeeMachineUtils.toHexString(self.machineId)) {
        self.machine = peripheral;
        
        try {
          self.setState(MACHINE_STATE.CONNECTING)
          await peripheral.connectAsync();
          self.setState(MACHINE_STATE.CONNECTED)
          noble.stopScanning();
          console.log(peripheral.advertisement.manufacturerData)
        } catch (e) {
          self.setState(MACHINE_STATE.DISCONNECTED)
          throw e;
        }
      }
    })
```

**Comment by mteichtahl** [comment]
Any feedback would be greatly appreciated

**Comment by Nekonika** [comment]
Hello mteichtahl,
I am currently working on a similar approach in C# and figured, that just reading from P_MODE_READ every 10 seconds gets the job done aswell.
As for why the Manufacturer data seems to vary - I have no clue. I just don't get any manufacturer data at all in the advertisements of my "BlueFrog". 
To get the key, I just read data from an encoded endpoint and bruteforce the key by decoding the data until the first byte matches the key used.
Hope this helps. ^^

**Comment by mteichtahl** [comment]
Thanks for the insight. I’ll try your suggestion of using P_MODE_READ. It still remains a mystery why the C++ code get a key of 2A in the first byte but node gets AB. Please note: My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule!Sent on the go - please excuse mistakes On 23 Feb 2024, at 6:07 am, Nekonika ***@***.***> wrote:﻿
Hello mteichtahl,
I am currently working on a similar approach in C# and figured, that just reading from P_MODE_READ every 10 seconds gets the job done aswell.
As for why the Manufacturer data seems to vary - I have no clue. I just don't get any manufacturer data at all in the advertisements of my "BlueFrog".
To get the key, I just read data from an encoded endpoint and bruteforce the key by decoding the data until the first byte matches the key used.
Hope this helps. ^^

**Comment by mteichtahl** [comment]
To close out. The issue was the underlying firmware on the pi. We had to update the firmware to the latest. Once done the problem was resolved.
