### ISSUE TITLE
No Machinefiles in J.O.E App

### ISSUE THREAD

**Issue by Spiderschwein** [Jutta-Proto/protocol-bt-cpp#16]
Hey,

I have no Folder "machinefiles" in the JOE App? Am I missing something? Is this a version thing?

What exactly is in the machinefiles? So maybe they have moved the information somewhere else.

![grafik](https://github.com/Jutta-Proto/protocol-bt-cpp/assets/3458624/7c127b59-fd28-4d47-9268-5079c1361d6f)

Thanks in adavance.

**Comment by COM8** [comment]
They relocated them. They are now inside `assets/documents/xml`. Sneaky sneaky :D

**Comment by COM8** [comment]
I updated the docs. Tanks for reporting @Spiderschwein!
https://github.com/Jutta-Proto/protocol-bt-cpp/commit/7dd5a31151cfb522d6c999e1332ee063ae11ee76

**Comment by Spiderschwein** [comment]
Ah wow, thanks for your fast response.
Under documents, interesting. Not sure, if I had found them there :D
