### ISSUE TITLE
Statistics via Bluetooth

### ISSUE THREAD

**Issue by tobru** [Jutta-Proto/protocol-bt-cpp#2]
I'm mostly interested in reading statistics via Bluetooth. It seems that "Statistics Command" and "Statistics Data" isn't documented yet. Is there any chance to get more information about it?

**Comment by COM8** [comment]
Yes, I would love to provide this functinality.
Currently I'm working on an update for the [gtk-ui](https://github.com/Jutta-Proto/gtk-ui/tree/bt) so I can actually show the stuff I found out. Probably by the end of February I can have a look at it.

**Comment by tronicum** [comment]
i would also love statistics. also if cleaning or filter change is required. anything we can do to help?

**Comment by COM8** [comment]
I'm currently getting back into investigating the WIFI connection, so nothing new on that front. But in case know a bit of C++ and you own a bt dongle, you can try looking at interpreting them. Let me know if you are interested, than I could write a run down about how one would look into this.

**Comment by COM8** [comment]
```log
[  info  ] [thread 164287]      Read statistics data: 00014E00000000002700009800000A00FFFF00000300FFFF00000900FFFF00FFFF00FFFF00FFFF00006700FFFF00FFFF00FFFF00000000000200000000FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00FFFF00000000000000000000000000FFFF00FFFF00FFFF00FFFF00000000000000000000000000FFFF00FFFF00FFFF00FFFF00000000000000000000000000FFFF00FFFF00FFFF00FFFF0000000000000000000000000000000000000000000000000000000000000000
[  info  ] [thread 164287]      Total number of products: 334
[ debug  ] [thread 164287]      Product Espresso: 39
[ debug  ] [thread 164287]      Product Coffee: 152
[ debug  ] [thread 164287]      Product Cappuccino: 10
[ debug  ] [thread 164287]      Product Espresso Macchiato: 3
[ debug  ] [thread 164287]      Product Milk Foam: 9
[ debug  ] [thread 164287]      Product Hotwater Portion(normal): 103
[ debug  ] [thread 164287]      Product Cafe Barista: 0
[ debug  ] [thread 164287]      Product Barista Lungo: 0
[ debug  ] [thread 164287]      Product Espresso Doppio: 0
[ debug  ] [thread 164287]      Product 2 Espressi: 2
[ debug  ] [thread 164287]      Product 2 Coffee: 0
```

Never mind. Currently working on a PR with docs for this feature.
https://github.com/Jutta-Proto/protocol-bt-cpp/pull/5

**Comment by tronicum** [comment]
Awesome. Danke!!
