### ISSUE TITLE
Heartbeat Encoding example wrong?

### ISSUE THREAD

**Issue by Masltov** [Jutta-Proto/protocol-bt-cpp#3]
I try to replicate encDecBytes on another platform. 
Unfortunately I get slightly different results for your example in the readme in section "Heartbeat".

So providing input `0x 00 7F 80` shall result in encoded/decoded `0x 77 65 6D` 
but I get `0x 3B 65 6D`, which is close but not equal.

Do you have another input/output combination for verification?
Thanks!

**Comment by COM8** [comment]
I will have a look at it tomorrow.

**Comment by COM8** [comment]
You probably forgot to set the key to the first byte:
[`encodedData[0] = manData.key;`](https://github.com/Jutta-Proto/protocol-bt-cpp/blob/9ada0c0f9b8bfe62cf68c16da50743ef48a27e96/src/jutta_bt_proto/CoffeeMaker.cpp#L222)
