### ISSUE TITLE
GTK-based program using BT protocol crashes with segmentation fault error

### ISSUE THREAD

**Issue by sergey-gra** [Jutta-Proto/protocol-bt-cpp#7]
Greetings,

I attempted to execute a gtk-based example program using the BT (Bluetooth) protocol. Upon successfully building the program, I proceeded to run it. However, upon clicking the "Connect" button, the application crashed after a few seconds. Below is the log output:

[ info ] [thread 50639] Launching Version: 0.0.0 dev
[ info ] [thread 50639] Coffee maker found!
[ info ] [thread 50646] Scan stopped
[ info ] [thread 50646] Loading machines...
[ info ] [thread 50646] Loaded 484 machines.
Segmentation fault

**Comment by sergey-gra** [comment]
After conducting further debugging, it was discovered that the line of code

`tinyxml2::XMLElement* joe = doc.FirstChildElement("JOE"); `

is resulting in a null pointer being returned.

After encountering the issue a modification was made to the code.  The original line of code `tinyxml2::XMLElement* joe = doc.FirstChildElement("JOE");` was replaced with the following code block: 
doc.LoadFile(path.c_str());
```
if (doc.Error()){
    /*error occurred*/
    std::cout << "Error loading XML file: " <<  doc.ErrorStr() << std::endl;
}
```

 This modification was successful in resolving the issue and allowing the program to execute as intended.

**Comment by sergey-gra** [comment]
As I suppose the problem not in the source code but in my mistake. I built a program using  `-DCMAKE_BUILD_TYPE=Release`  flag that's why maybe the asserts are ignored.

**Comment by COM8** [comment]
Thanks for reporting! What coffee maker are you using?
It should state this when starting in: `"Loading JOE from '{}'..."`, where `{}` is the coffee maker file.

This issue might indicate an unsupported coffee maker in my implementation or an edge case.

**Comment by sergey-gra** [comment]
Thank you for your response. I am currently utilizing the Jura E6(EU) 2020 model coffee machine. When establishing a connection to the machine, it generates the following output: "Loading JOE from 'machinefiles/EF532V2.xml'..." subsequent to the identification of the machine as 'E6 (EB)' Version 5 with 11 products.'

**Comment by COM8** [comment]
Hmmm, on my side this one works. Could you please quickly validate the content of the XML file here: https://www.xmlvalidation.com

**Comment by sergey-gra** [comment]
Upon conducting a validation of the XML file, the output generated was "No errors were found".
Subsequent to rebuilding the project with the '-DCMAKE_BUILD_TYPE=Debug' flag, I was able to successfully execute the solution on my end. Based on my observations, it is possible that the issue was related to the behavior of asserts when the program is run in Release mode.

**Comment by COM8** [comment]
Glad you were able to run it!

But those asserts should not change anything in the control flow (except failing early in case an assertion is invalid).

**Comment by sergey-gra** [comment]
Indeed, it is correct that asserts should not alter the control flow of a program. However, the use of the 'assert' function in the following line of code: `assert(doc.LoadFile(path.c_str()) == tinyxml2::XML_SUCCESS);`, indicates that a function is being called within the scope of the assert. In the case where asserts are ignored in Debug mode, it is possible for this function to remain uncalled, which can lead to the return of a null pointer from the subsequent line of code: `tinyxml2::XMLElement* joe = doc.FirstChildElement("JOE");`

**Comment by COM8** [comment]
Ah, now I see, what you mean! Thanks. Fixed it.

**Comment by COM8** [comment]
Honestly, such a bug is embarrassing 🫣. I don't know what I was thinking at this time.

**Comment by sergey-gra** [comment]
Acknowledging a mistake is a sign of professionalism and a valuable learning opportunity. We all make mistakes, and it is important to reflect on them to ensure that we learn from them and improve in the future. While it may be embarrassing to discover a bug or error, it is essential to address it promptly and move forward with the goal of improving the overall quality of the software  :blush:

**Comment by COM8** [comment]
Agree! 😄
